//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator.Couche_middleware {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="generator", ConfigurationName="Couche_middleware.IcomposantService")]
    public interface IcomposantService {
        
        [System.ServiceModel.OperationContractAttribute(Action="generator/IcomposantService/connection", ReplyAction="generator/IcomposantService/connectionResponse")]
        Common.STG connection(Common.STG oSTG);
        
        [System.ServiceModel.OperationContractAttribute(Action="generator/IcomposantService/connection", ReplyAction="generator/IcomposantService/connectionResponse")]
        System.Threading.Tasks.Task<Common.STG> connectionAsync(Common.STG oSTG);
        
        [System.ServiceModel.OperationContractAttribute(Action="generator/IcomposantService/callback", ReplyAction="generator/IcomposantService/callbackResponse")]
        void callback(string reponse);
        
        [System.ServiceModel.OperationContractAttribute(Action="generator/IcomposantService/callback", ReplyAction="generator/IcomposantService/callbackResponse")]
        System.Threading.Tasks.Task callbackAsync(string reponse);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IcomposantServiceChannel : Generator.Couche_middleware.IcomposantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IcomposantServiceClient : System.ServiceModel.ClientBase<Generator.Couche_middleware.IcomposantService>, Generator.Couche_middleware.IcomposantService {
        
        public IcomposantServiceClient() {
        }
        
        public IcomposantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IcomposantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcomposantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcomposantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.STG connection(Common.STG oSTG) {
            return base.Channel.connection(oSTG);
        }
        
        public System.Threading.Tasks.Task<Common.STG> connectionAsync(Common.STG oSTG) {
            return base.Channel.connectionAsync(oSTG);
        }
        
        public void callback(string reponse) {
            base.Channel.callback(reponse);
        }
        
        public System.Threading.Tasks.Task callbackAsync(string reponse) {
            return base.Channel.callbackAsync(reponse);
        }
    }
}
